# Generated by Django 5.1.4 on 2024-12-13 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_img', models.ImageField(upload_to='gambar_album/')),
                ('nama', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='ProfilArtis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('sampul_foto', models.ImageField(upload_to='sampul_foto')),
            ],
            options={
                'verbose_name': 'Profil Artis',
                'verbose_name_plural': 'Profil Artis',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_img', models.ImageField(upload_to='gambar_playlist')),
                ('nama', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Playlist Musik',
                'verbose_name_plural': 'Playlist Musik',
            },
        ),
        migrations.CreateModel(
            name='Lagu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('audio_img', models.ImageField(upload_to='gambar_audio')),
                ('audio_file', models.FileField(upload_to='file_audio')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.genre')),
                ('playlist', models.ManyToManyField(blank=True, to='base.playlist')),
                ('artis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profilartis')),
            ],
            options={
                'verbose_name': 'Lagu',
                'verbose_name_plural': 'Lagu',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profilartis'),
        ),
    ]
