# Generated by Django 5.1.4 on 2024-12-13 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_img', models.ImageField(upload_to='gambar_album/')),
                ('nama', models.CharField(max_length=100)),
                ('artis', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Playlist Musik',
                'verbose_name_plural': 'Playlist Musik',
            },
        ),
        migrations.CreateModel(
            name='Lagu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('artis', models.CharField(max_length=100)),
                ('audio_img', models.ImageField(upload_to='gambar_audio')),
                ('audio_file', models.FileField(upload_to='file_audio')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.genre')),
                ('playlist', models.ManyToManyField(blank=True, null=True, to='base.playlist')),
            ],
            options={
                'verbose_name': 'Lagu',
                'verbose_name_plural': 'Lagu',
            },
        ),
    ]
