# Generated by Django 5.1.4 on 2024-12-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_playlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_img',
            field=models.ImageField(default='', upload_to='gambar_playlist'),
            preserve_default=False,
        ),
    ]
