# Generated by Django 5.1.4 on 2024-12-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_playlist_playlist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='lagu',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='base.lagu'),
        ),
        migrations.AlterField(
            model_name='lagu',
            name='playlist',
            field=models.ManyToManyField(blank=True, related_name='lagus', to='base.playlist'),
        ),
    ]
