# Generated by Django 5.1.4 on 2024-12-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_playlist_lagu_alter_lagu_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='lagu',
        ),
        migrations.AlterField(
            model_name='lagu',
            name='playlist',
            field=models.ManyToManyField(blank=True, null=True, to='base.playlist'),
        ),
    ]
